---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: harbor-scanner-anchore
  labels:
    app: harbor-scanner-anchore
spec:
  selector:
    matchLabels:
      app: harbor-scanner-anchore
  replicas: 1
  template:
    metadata:
      labels:
        app: harbor-scanner-anchore
    spec:
      containers:
        - name: adapter
          image: anchore/harbor-scanner-adapter:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: SCANNER_ADAPTER_LISTEN_ADDR
              value: ":8080"
            - name: ANCHORE_ENDPOINT
              value: "http://192.168.49.13:8228"
            - name: ANCHORE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: anchore-creds
                  key: username
            - name: ANCHORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: anchore-creds
                  key: password
            - name: ANCHORE_CLIENT_TIMEOUT_SECONDS
              value: "60"
            - name: SCANNER_ADAPTER_FILTER_VENDOR_IGNORED
              value: "true"
            - name: SCANNER_ADAPTER_LOG_LEVEL
              value: "debug"
            - name: SCANNER_ADAPTER_REGISTRY_TLS_VERIFY
              value: "false"
            - name: SCANNER_ADAPTER_IGNORE_HARBOR_CREDS
              value: "true"
# To enable api authentication, uncomment this and set it to a good randomized value. Use that same value in the scanner config in Harbor UI with "Bearer" type
#            - name: "SCANNER_ADAPTER_APIKEY"
#              value: "apikey123"

# Uncomment below to enable https in api
#            - name: SCANNER_ADAPTER_TLS_KEY_FILE
#              value: "/certs/tls.key"
#            - name: SCANNER_ADAPTER_TLS_CERT_FILE
#              value: "/certs/tls.crt"

#          volumeMounts:
#            - name: certs
#              mountPath: /certs
#          ports:
#            - containerPort: 8080
#      volumes:
#        - name: certs
#          secret:
#            secretName: adapter-certs
---
apiVersion: v1
kind: Service
metadata:
  name: harbor-scanner-anchore
spec:
  selector:
    app: harbor-scanner-anchore
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
